### Begin hier
Begin met het runnen van deze blokken code.  
Deze zijn verantwoordelijk voor imports, setup, dependencies en andere zaken. 

In [1]:
# Imports
import pandas as pd
import cv2
import numpy as np
from matplotlib import pyplot as plt
import data_generator as dgen

print("Succes loading Imports")

Succes loading Imports


In [2]:
# Functions
def get_file_name(path):
    file_name = path[path.rfind('/') + 1:]
    # Splits out the file-type designation
    file_name, file_extension = file_name.split('.')
    return file_name
    
print("Succes loading Functions")

Succes loading Functions


### Heb je al data?
Als er al trainingsdata bestaat, schrijf dan simpelweg de filename bij het betreffende blok.  
Run anders het blok waarin de data nog word gegenereerd. 

In [3]:
"""Ik heb geen data"""
# Start here if no data has been generated.

print("Provide the path to a video file.\n"
      "  (Example: C:/Users/admin/video/video.mp4)")

vid_path = input("Provide a video path: ")
vid_name = get_file_name(vid_path)
print(f"Provided path: '{vid_path}',\nfound filename: '{vid_name}'")
print("")

generator = dgen.Generator(vid_path)
generator.generate_data()
print(f"Video has been processed and exported to {generator.file_name}__trainingsData.mp4")
print(f"Data generated and exported to {generator.file_name}_trainingsData.json")
print("")

try: 
      data_path = f"generateData_OUTPUT/{vid_name}_trainingsData.json"
      frame_data = pd.read_json(data_path, orient='index')
except Exception as e:
      print(f"Something went wrong.\n {e}")


print("The data-table was loaded. \nTotal Table size: ")
print(f"Rows: {frame_data.shape[0]}, Columns: {frame_data.shape[1]}")

Provide the path to a video file.
  (Example: C:/Users/admin/video/video.mp4)


ValueError: not enough values to unpack (expected 2, got 1)

In [4]:
"""Ik heb al trainingsdata. """
# Start here if data has already been generated.
print("Provide the filename to a file in "
      "the generateData_OUTPUT folder.\n"
      "Example: perfect_example_trainingsData")
      
data_path = input("Filename: ")
vid_name = get_file_name(data_path)
print(f"Provided path: {data_path}")

try: 
      data_path = f"generateData_OUTPUT/{vid_name}.json"
      frame_data = pd.read_json(data_path, orient='index')
except Exception as e:
      print(f"Something went wrong.\n {e}")

print("\nTotal Table size: ")
print(f"Rows: {frame_data.shape[0]}, Columns: {frame_data.shape[1]}")

Provide the filename to a file in the generateData_OUTPUT folder.
Example: perfect_example_trainingsData
Provided path: generateData_OUTPUT/GOPR1124_Trim_trainingsData.json

Total Table size: 
Rows: 18646, Columns: 482


In [ ]:
# cycle_data = pd.read_csv("dataset bike/220316_1023_JOS.csv", sep=";")
# cycle_data.head()
#
# maxhr = max(cycle_data["idHeartrate"])
# cycle_data['heartRateZone'] = cycle_data.apply(
#     lambda row: 5 if (row.idHeartrate > (maxhr * 0.9)) else (
#         4 if (row.idHeartrate > (maxhr * 0.8)) else (
#             3 if (row.idHeartrate > (maxhr * 0.7)) else (
#                 2 if (row.idHeartrate > (maxhr * 0.6)) else (
#                     1 if (row.idHeartrate > (maxhr * 0.5)) else (0))))), axis=1)

In [5]:
frame_data.head()

TS  HR  PWR  heartRateZone  \
1  505  85   50              0   
2  505  85   50              0   
3  505  85   50              0   
4  505  85   50              0   
5  505  85   50              0   

                                                   0  \
1  [[0.557644486427307, 0.648186445236206, -0.040...   
2  [[0.557781159877777, 0.652138113975524, -0.040...   
3  [[0.5626065135002131, 0.656960010528564, -0.04...   
4  [[0.561814308166503, 0.6575654745101921, -0.04...   
5  [[0.5678303241729731, 0.663326919078826, -0.03...   

                                                   1  \
1  [[0.557483077049255, 0.552068829536438, -0.076...   
2  [[0.5576397776603691, 0.555081248283386, -0.07...   
3  [[0.5579067468643181, 0.556771099567413, -0.07...   
4  [[0.559345841407775, 0.5556150674819941, -0.07...   
5  [[0.5601344108581541, 0.554888725280761, -0.07...   

                                                   2  \
1  [[0.553551793098449, 0.5780954957008361, -0.04...   
2  [[0.5538336634635921, 0.5809364914894101, -0.0...   
3  [[0.554864883422851, 0.582704246044158, -0.041...   
4  [[0.555837929248809, 0.58216106891632, -0.0412...   
5  [[0.556598603725433, 0.581692636013031, -0.040...   

                                                   3  \
1  [[0.54665207862854, 0.46006208658218306, -0.05...   
2  [[0.547837734222412, 0.46182113885879505, -0.0...   
3  [[0.5476696491241451, 0.463245302438735, -0.05...   
4  [[0.548979759216308, 0.46244707703590304, -0.0...   
5  [[0.5491563081741331, 0.460878789424896, -0.05...   

                                                   4  \
1  [[0.558870553970336, 0.5247067213058471, -0.08...   
2  [[0.5592626929283141, 0.527342796325683, -0.08...   
3  [[0.559209465980529, 0.528769314289093, -0.080...   
4  [[0.560742497444152, 0.527681291103363, -0.080...   
5  [[0.5613942146301271, 0.526626706123352, -0.08...   

                                                   5  ...  \
1  [[0.559488832950592, 0.48826456069946206, -0.0...  ...   
2  [[0.56026405096054, 0.490500211715698, -0.0747...  ...   
3  [[0.560060918331146, 0.49175029993057207, -0.0...  ...   
4  [[0.5615682601928711, 0.490862190723419, -0.07...  ...   
5  [[0.561959207057952, 0.489454329013824, -0.074...  ...   

                                                 468  \
1  [[0.480815052986145, 0.37191823124885504, 0.00...   
2  [[0.48186632990837003, 0.372595608234405, 0.00...   
3  [[0.482597649097442, 0.37554320693016, 0.00381...   
4  [[0.48320049047470004, 0.37472867965698203, 0....   
5  [[0.48083800077438305, 0.37290006875991805, 0....   

                                                 469  \
1  [[0.49536809325218206, 0.371358275413513, 0.00...   
2  [[0.496729910373687, 0.37259367108345004, 0.00...   
3  [[0.49783867597579906, 0.37549942731857305, 0....   
4  [[0.49830114841461104, 0.37439942359924305, 0....   
5  [[0.495698124170303, 0.372656464576721, 0.0036...   

                                                 470  \
1  [[0.480778813362121, 0.34924191236495905, 0.00...   
2  [[0.48208233714103704, 0.349857658147811, 0.00...   
3  [[0.482793241739273, 0.35240229964256203, 0.00...   
4  [[0.48332807421684204, 0.35114678740501404, 0....   
5  [[0.48110470175743103, 0.348926812410354, 0.00...   

                                                 471  \
1  [[0.46612980961799605, 0.37237301468849104, 0....   
2  [[0.466910362243652, 0.37237179279327304, 0.00...   
3  [[0.46731585264205905, 0.37538290023803705, 0....   
4  [[0.46801066398620605, 0.37484848499298, 0.005...   
5  [[0.46586400270462003, 0.37290182709693903, 0....   

                                                 472  \
1  [[0.48077648878097506, 0.39444035291671703, 0....   
2  [[0.481569498777389, 0.39509481191635104, 0.00...   
3  [[0.48236334323883, 0.39839088916778503, 0.003...   
4  [[0.48302134871482805, 0.39804667234420704, 0....   
5  [[0.480530679225921, 0.396575450897216, 0.0036...   

                                                 473  \
1  [[0

In [13]:
X = frame_data.drop(columns=['TS', 'HR', 'PWR', 'heartRateZone'])
Y = frame_data["heartRateZone"]

#print(y)

0  \
1  [[0.557644486427307, 0.648186445236206, -0.040...   
2  [[0.557781159877777, 0.652138113975524, -0.040...   
3  [[0.5626065135002131, 0.656960010528564, -0.04...   
4  [[0.561814308166503, 0.6575654745101921, -0.04...   
5  [[0.5678303241729731, 0.663326919078826, -0.03...   

                                                   1  \
1  [[0.557483077049255, 0.552068829536438, -0.076...   
2  [[0.5576397776603691, 0.555081248283386, -0.07...   
3  [[0.5579067468643181, 0.556771099567413, -0.07...   
4  [[0.559345841407775, 0.5556150674819941, -0.07...   
5  [[0.5601344108581541, 0.554888725280761, -0.07...   

                                                   2  \
1  [[0.553551793098449, 0.5780954957008361, -0.04...   
2  [[0.5538336634635921, 0.5809364914894101, -0.0...   
3  [[0.554864883422851, 0.582704246044158, -0.041...   
4  [[0.555837929248809, 0.58216106891632, -0.0412...   
5  [[0.556598603725433, 0.581692636013031, -0.040...   

                                                   3  \
1  [[0.54665207862854, 0.46006208658218306, -0.05...   
2  [[0.547837734222412, 0.46182113885879505, -0.0...   
3  [[0.5476696491241451, 0.463245302438735, -0.05...   
4  [[0.548979759216308, 0.46244707703590304, -0.0...   
5  [[0.5491563081741331, 0.460878789424896, -0.05...   

                                                   4  \
1  [[0.558870553970336, 0.5247067213058471, -0.08...   
2  [[0.5592626929283141, 0.527342796325683, -0.08...   
3  [[0.559209465980529, 0.528769314289093, -0.080...   
4  [[0.560742497444152, 0.527681291103363, -0.080...   
5  [[0.5613942146301271, 0.526626706123352, -0.08...   

                                                   5  \
1  [[0.559488832950592, 0.48826456069946206, -0.0...   
2  [[0.56026405096054, 0.490500211715698, -0.0747...   
3  [[0.560060918331146, 0.49175029993057207, -0.0...   
4  [[0.5615682601928711, 0.490862190723419, -0.07...   
5  [[0.561959207057952, 0.489454329013824, -0.074...   

                                                   6  \
1  [[0.5597543716430661, 0.399806082248687, -0.03...   
2  [[0.5613132119178771, 0.400953352451324, -0.03...   
3  [[0.561062157154083, 0.401896983385086, -0.036...   
4  [[0.562443733215332, 0.40163508057594305, -0.0...   
5  [[0.5620711445808411, 0.39940199255943304, -0....   

                                                   7  \
1  [[0.4580779671669, 0.381644248962402, 0.011037...   
2  [[0.458215415477752, 0.38104885816574, 0.00945...   
3  [[0.45929083228111206, 0.385342180728912, 0.00...   
4  [[0.460250437259674, 0.384892582893371, 0.0105...   
5  [[0.45851713418960505, 0.38311368227005005, 0....   

                                                   8  \
1  [[0.56100183725357, 0.33718937635421703, -0.02...   
2  [[0.562924325466156, 0.337617397308349, -0.025...   
3  [[0.5624566674232481, 0.335103631019592, -0.02...   
4  [[0.5639521479606621, 0.33521533012390103, -0....   
5  [[0.563142716884613, 0.331407845020294, -0.025...   

                                                   9  ...  \
1  [[0.5622510910034181, 0.30542916059494, -0.026...  ...   
2  [[0.5644397139549251, 0.30456727743148804, -0....  ...   
3  [[0.5636905431747431, 0.301431804895401, -0.02...  ...   
4  [[0.5652977824211121, 0.30157762765884405, -0....  ...   
5  [[0.56433629989624, 0.297170549631118, -0.0272...  ...   

                                                 468  \
1  [[0.480815052986145, 0.37191823124885504, 0.00...   
2  [[0.48186632990837003, 0.372595608234405, 0.00...   
3  [[0.482597649097442, 0.37554320693016, 0.00381...   
4  [[0.48320049047470004, 0.37472867965698203, 0....   
5  [[0.48083800077438305, 0.37290006875991805, 0....   

                                                 469  \
1  [[0.49536809325218206, 0.371358275413513, 0.00...   
2  [[0.496729910373687, 0.37259367108345004, 0.00...   
3  [[0.49783867597579906, 0.37549942731857305, 0....   
4  [[0.49830114841461104, 0.37439942359924305, 0....   
5  [[0.495698124170303, 0.37265646

In [69]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras import backend as K
from keras.layers import Layer
from keras.models import Model
from keras.layers import Input
from keras.layers import Dense
from keras.layers import Dense, Input, Concatenate, Lambda

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)
Y_train.head()

5609     3
14349    5
18527    5
11434    5
15575    5
Name: heartRateZone, dtype: int64

In [70]:
inputTensor = Input(shape=(1434,))
layers = []

for i in range(0, 1431, 3):
    layers.append(Lambda(lambda x: x[:,i: i+3], output_shape=((3,)))(inputTensor))
for i in range(0, 477):
    layers[i] = Dense(1)(layers[i])
coordslayer = Concatenate()(layers)

hidden1 = Dense(477*2, activation='relu')(coordslayer)
hidden2 = Dense(477, activation='relu')(hidden1)
hidden3 = Dense(240, activation='relu')(hidden2)
hidden4 = Dense(100, activation='relu')(hidden3)
hidden5 = Dense(20, activation='relu')(hidden4)

outputTensor = Dense(5, activation='sigmoid')(hidden5)
model = Model(inputs=inputTensor, outputs=outputTensor)

In [72]:
print(model.summary())

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 1434)]       0           []                               
                                                                                                  
 lambda (Lambda)                (None, 3)            0           ['input_1[0][0]']                
                                                                                                  
 lambda_1 (Lambda)              (None, 3)            0           ['input_1[0][0]']                
                                                                                                  
 lambda_2 (Lambda)              (None, 3)            0           ['input_1[0][0]']                
                                                                                              

In [73]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [74]:
model.fit(X, Y, epochs=150, batch_size=10)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type list).

In [ ]:
# evaluate the keras model
_, accuracy = model.evaluate(X, Y)
print('Accuracy: %.2f' % (accuracy*100))

In [66]:
x = np.array([[0,00,000], [1,11,111], [2,22,222], [3,33,333]])
print(x[:,:])
print(x[:,0:3])
g = lambda g: g[:,2:4]
print(g(x))

[[  0   0   0]
 [  1  11 111]
 [  2  22 222]
 [  3  33 333]]
[[  0   0   0]
 [  1  11 111]
 [  2  22 222]
 [  3  33 333]]
[[  0]
 [111]
 [222]
 [333]]
